### ISSUE TITLE
How is `automatic_rewritten_utterance` generated?

### ISSUE THREAD

**Issue by littlewine** [daltonj/treccastweb#4]
Hello,

I would like to ask what kind of system was used to create the `automatic_rewritten_utterance` field (query rewrite baseline) provided. 
Is there any description of the system somewhere?

Thank you in advance

**Comment by daltonj** [comment]
It is from:
https://github.com/thunlp/ConversationQueryRewriter

There are also now more recent models that will be used in the coming year.  One under considerations is a T5 model used by the h2oloo team this year:
https://huggingface.co/castorini/t5-base-canard

**Comment by littlewine** [comment]
Thank you!
